<body>
    <div class="container martop-20">    
    <?php    
    if($_REQUEST['m']) { 
        $msg = (int) $_REQUEST['m']; 
        $class = "alert alert-success";

        if($msg == 1) {
          $message = "Pacientes foram importados com sucesso!"; 
          $message.= " <strong>Total de Pacientes importados " . $_REQUEST['t'] . '</strong>'; 
        }

        if($msg == 2) {          
          $class = "alert alert-danger";   
          $message = "É preciso enviar arquivo com a <strong>extensão .txt!</strong>";
        }        
    ?>     
    <div class="<?=$class?>"><?=$message?></div>
    <?php 
        }
    ?>     
        <form action="/patients/import" method="POST" enctype="multipart/form-data">
        <legend>Cadastro de Paciente</legend>

            <div class="form-grou col-md-8">
            <small id="emailHelp" class="form-text text-muted">Envie um arquivo txt com os pacientes</small>
            <input type="file" name="patients" class="form-control">    
            </div>            

            <div class="form-group col-md-8 martop-20">            
            <input type="submit" value="Enviar" class="btn btn-primary form-control">
            </div>
                
        </form>
    </div>
</body>