<body>
    <div class="container martop-20">         
        <form action="/patients/insert" method="POST">
        <legend>Cadastro de Paciente</legend>

            <div class="form-grou col-md-8">
            <small id="emailHelp" class="form-text text-muted">Insira o nome do paciente</small>
            <input type="text" name="name" class="form-control">    
            </div>

            <div class="form-group col-md-8">
            <small id="emailHelp" class="form-text text-muted">Insira a idade do paciente</small>
            <input type="text" name="age" class="form-control" >
            </div>

            <div class="form-group col-md-8">
            <small id="emailHelp" class="form-text text-muted">Insira o Telefone do Paciente</small>
            <input type="text" name="telephone" class="form-control">
            </div>

            <div class="form-group col-md-8">            
            <input type="submit" value="Inserir" class="btn btn-primary form-control">
            </div>
                
        </form>
    </div>
</body>